### ISSUE TITLE
Implement upgrade of the cluster

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubeone#1]
This issue tracks progress on implementing cluster upgrades with KubeOne.

**Acceptance criteria:**
* [x] Operator can upgrade KubeOne cluster using command such `kubeone upgrade` (#211)
* [x] `kubeone upgrade` takes care of upgrading workers (MachineDeployments) (#214)
* [x] `kubeone upgrade` takes care of upgrading components we deploy on the cluster, such as `machine-controller` and Ark (#236)
* [x] We're testing do upgrades work correctly as part of our E2E tests

**Planning:**
* [x] Write a proposal for handling cluster upgrades (#190)

**Implementation:**
* [x] Create `kubeone upgrade` CLI command (#196, #201)
* [x] Implement preflight checks (#206)
* [x] Implement core scripts and logic for running upgrades (package upgrades and `kubeadm upgrade`) (#211)
* [x] Upgrade MachineDeployments after upgrading control plane nodes (#214)

**Consider:**
* [ ] Backup critical components before running upgrade process
* [ ] Build add-on manager for managing and updating components we deploy on cluster, such as `machine-controller` and Ark
