### ISSUE TITLE
Support Kubernetes 1.23

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1670]
This is a collector issue for Kubernetes 1.23 support in KubeOne. The following tasks should be taken care of:

* [x] Check the changelog to ensure there are no breaking changes and removals
* [x] Update the kubeone-e2e image to add test binaries for Kubernetes 1.23 (#1676)
* [x] Add E2E tests for Kubernetes 1.23 (#1678)
* [x] Update daily periodics to use Kubernetes 1.23
* [x] Update the Compatibility Matrix (https://github.com/kubermatic/docs/pull/878)
* [x] Create an issue to track updating [images](https://github.com/kubermatic/kubeone/blob/master/pkg/templates/images/images.go) (#1685)
* [x] Run the full conformance tests suite using Sonobuoy

**Action items:**

* [x] Create an issue template based on this issue (#1702)

/assign
