### ISSUE TITLE
Add CSI drivers for remaining providers

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#1710]
**What feature would you like to be added?**

This is a collector issue for adding CSI drivers for remaining providers. We already added support for all CSI drivers that work. The remaining drivers are:

* [x] DigitalOcean -- doesn't support Kubernetes 1.22+ clusters (ref: https://github.com/kubermatic/kubeone/issues/1567#issuecomment-944215463)
* [ ] Equinix Metal -- doesn't have a CSI driver (ref: https://github.com/kubermatic/kubeone/issues/1569#issuecomment-952819355)
* [ ] GCP -- we don't support GCP CCM (ref: https://github.com/kubermatic/kubeone/issues/1568#issuecomment-956113744)
