### ISSUE TITLE
Cluster Backups

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubeone#2]
This issue tracks progress on adding Cluster Backups as a feature. As discussed on Slack and on the team meetings, it is decided to use [Heptio Ark](https://github.com/heptio/ark) to handle backups for both `etcd` and the cluster as a whole.

**Acceptance criteria:**

* [ ] We're doing frequent `etcd` backups
* [ ] We're doing frequent cluster backups
* [ ] User can choose between storing backups on the cluster or in the cloud

**Decisions to be made:**

* [x] #52: Decide how we want to handle etcd backups
* [x] #53: Decide how to handle Ark manifests
* [x] #54: Decide where to store information about backups and backups location

**Subtasks**:

* [x] #49: Deploy Heptio Ark on KubeOne clusters (#61)
* [x] #132: Deploy Restic along with Ark to support snapshots of additional volume types (#136)
* [x] ~#50: Deploy Minio on KubeOne clusters~
* [x] #52: Modify etcd deployment to include Ark BackupHook used to backup etcd (#127)
* [ ] #24: Create Ark Schedule (CronJob) to automatically backup etcd (#130)
* [ ] #25: Cleanup old etcd backups (#130)
* [ ] #133: Support providing credentials for other Ark supported platforms
* [ ] #51: Document how we deploy and use Heptio Ark

**Comment by xmudrii** [comment]
It is decided that this is out of scope
/close
