### ISSUE TITLE
Support Kubernetes 1.24

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2010]
This is a collector issue for Kubernetes 1.24 support in KubeOne. Kubernetes 1.24 is scheduled for May 3rd. The following tasks should be taken care of:

* [x] Check the Kubernetes changelog to ensure there are no breaking changes and removals
* [x] Update [the `kubeone-e2e` image](https://github.com/kubermatic/kubeone/tree/master/hack/images/kubeone-e2e) to add the needed Kubernetes test binaries (#2016)
* [x] Update [default admission controllers](https://github.com/kubermatic/kubeone/blob/master/pkg/kubeflags/data.go) if needed (not needed)
* [x] Add E2E tests (#2045)
* [x] Update daily periodics to use the latest Kubernetes release
* [x] Update [the Compatibility Matrix](https://docs.kubermatic.com/kubeone/master/architecture/compatibility/) (https://github.com/kubermatic/docs/pull/1066)
* [x] Create an issue to track updating [images](https://github.com/kubermatic/kubeone/blob/master/pkg/templates/images/images.go) (#2011)
* [x] Run the full conformance tests suite using [Sonobuoy](https://github.com/vmware-tanzu/sonobuoy)
