### ISSUE TITLE
Update images to support Kubernetes 1.24

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2011]
Action items:

- [x] Update the issue template to add/remove [images](https://github.com/kubermatic/kubeone/blob/master/pkg/templates/images/images.go) as appropriate

The following components/images should be updated:

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) (#2055, #2171)
- [x] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) (#2055, #2171)
- [x] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) (#2058, #2172)
- [x] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) (#2058, #2172)
- [x] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) (#2058, #2172)
- [x] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) (#2053)
- [x] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) (#2173)
- [x] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) (#2054, #2174)
- [x] [GCP CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) (#2176)
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) (already the latest)
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) (already the latest)
- [x] [Nutanix CSI](https://github.com/nutanix/helm) (#2182)
- [x] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) (#2061, #2151)
- [x] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) (#2061, #2151)
- [x] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) (#2169)
- [x] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) (#2050, #2169)
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) (#2052, #2175)
- [x] [NodeLocalDNS Cache](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) (#2079)
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) (#2079)

Relevant to #2010
