### ISSUE TITLE
Mirror registry deprecation for containerd 1.5

### ISSUE THREAD

**Issue by mate4st** [kubermatic/kubeone#2076]
registry.mirrors and registry.configs has been DEPRECATED in containerd v1.5. 

We need to upgrade the configuration of containerd to be conformant with the new handling of registries. 

https://github.com/containerd/containerd/blob/release/1.5/docs/cri/config.md

```[tasklist]
### Tasks
- [x] Check containerd v2 for any breaking API changes
- [x] Upgrade to the latest available 1.x version
- [ ] Migrate to the new config format available in 1.7+
```

**Comment by kron4eg** [comment]
While it's DEPRECATED, it still works. We don't need to upgrade before we upgrade to 1.6.

**Comment by xmudrii** [comment]
This might affect us for containerd 1.7, so we should double-check.
/remove-lifecycle stale

**Comment by kron4eg** [comment]
OSM has moved on to containerd2, KubeOne needs to update too.
