### ISSUE TITLE
Release KubeOne 1.5.0-rc.0

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2300]
### Before Release

* [x] Write and publish the changelog (#2312)
* [x] Create and push the release branch (`release/1.5`)
* [x] Update the Prow config
  * [x] Update the release jobs to add `release/v1.5` branch
  * [x] Update the `branchprotector` rules
  * [x] Update the `milestone_applier` rules
* [x] Update docs reference in KubeOne (#2314, #2315)
* [x] Update docs reference in the KubeOne repository (#2314, #2315)
* [x] Create docs for the release based on docs for the master branch (copy 
  `content/kubeone/master` to `content/kubeone/v1.5` in the
  [docs repo](https://github.com/kubermatic/docs)) (https://github.com/kubermatic/docs/pull/1179)

### Release

* [x] Create and push a new tag
* [x] Ensure that the release job has succeeded
  (watch https://public-prow.loodse.com/?job=post-kubeone-release)

### After Release

* [x] Update the release's description on the GitHub Releases page to replace
  the automatically generated description with the changelog
* [x] Download the binaries from GitHub and make sure that:
  * [x] Checksums are matching
  * [x] `kubeone version` returns the expected version
* [x] If the release introduces support for a new Kubernetes version, submit
  conformance results to https://github.com/cncf/k8s-conformance/ (https://github.com/cncf/k8s-conformance/pull/2121)

### Action Items

/assign
