### ISSUE TITLE
Support Kubernetes 1.25

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2307]
This is a collector issue for Kubernetes 1.25 support in KubeOne. The following tasks should be taken care of:

* [x] Check the Kubernetes changelog to ensure there are no breaking changes and removals
* [x] Update [the `kubeone-e2e` image](https://github.com/kubermatic/kubeone/tree/main/hack/images/kubeone-e2e) to update Sonobuoy (and other dependencies if needed) (#2404)
* [x] Update the latest supported Kubernetes version in [the API validation](https://github.com/kubermatic/kubeone/blob/main/pkg/apis/kubeone/validation/validation.go#L40-L41) (#2405)
* [x] Update [default admission controllers](https://github.com/kubermatic/kubeone/blob/main/pkg/kubeflags/data.go) if needed (not needed)
* [x] Update [the stable version marker in Makefile](https://github.com/kubermatic/kubeone/blob/5273f9a372736569c6b09b38f2959019d29e4d6a/Makefile#L24) (#2407)
* [x] Add E2E tests (#2405)
* [x] Update daily periodics to use the latest Kubernetes release
* [x] Update [the Compatibility Matrix](https://docs.kubermatic.com/kubeone/main/architecture/compatibility/supported-versions/) (https://github.com/kubermatic/docs/pull/1232)
* [x] Create an issue to track updating [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) (#2406)
* [ ] Run the full conformance tests suite using [Sonobuoy](https://github.com/vmware-tanzu/sonobuoy)
* [x] Update the issue template (#2405)

**Comment by gelbander** [comment]
Do you have an ETA for this?

**Comment by xmudrii** [comment]
@gelbander We plan to include this in KubeOne 1.6.0 which is planned for the end of February 2023.
