### ISSUE TITLE
Update images to support Kubernetes 1.25

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2406]
Action items:

- [x] Update the issue template to add/remove [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) as appropriate: #2479

The following components/images should be updated:

### General

- [Canal CNI](https://github.com/projectcalico/calico) (update on hold until https://github.com/projectcalico/calico/issues/5760 is not resolved)
- [Calico VXLAN CNI](https://github.com/projectcalico/calico) (update on hold until https://github.com/projectcalico/calico/issues/5760 is not resolved)
- [x] [Cilium CNI](https://github.com/cilium/cilium) (#2478)
- [x] [NodeLocalDNS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) (#2477)
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) (already the latest)
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) (#2476)

### Cloud provider components

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) (#2420)
- [x] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) (#2420)
- [x] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) (#2422)
- [x] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) (#2422)
- [x] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) (#2422)
- [x] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) (#2475)
- [x] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) (#2474)
- [x] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) (#2425)
- [x] [GCP Compute Persistent Disk CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) (#2471)
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) (#2426)
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) (already the latest)
- [x] [Nutanix CSI](https://github.com/nutanix/helm) (#2473)
- [x] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) (#2427)
- [x] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) (#2427)
- [x] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) (#2429)
- [x] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) (#2429)

Relevant to #2307
