### ISSUE TITLE
Update images to support Kubernetes 1.26

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2562]
The following components/images should be updated:

### General

- [x] [Cilium CNI](https://github.com/cilium/cilium) (#2582)
- [x] [NodeLocalDNS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) (#2580)
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) (#2580)
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) (#2580)

### Cloud provider components

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) (#2569)
- [x] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) (#2569)
- [x] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) (#2572)
- [x] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) (#2572)
- [x] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) (#2572)
- [x] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) (#2576)
- [x] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) (#2590)
- [x] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) (already the latest)
- [x] [GCP Compute Persistent Disk CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) (#2576)
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) (already the latest)
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) (#2578)
- [x] [Nutanix CSI](https://github.com/nutanix/helm) (already the latest)
- [x] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) (#2582)
- [x] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) (#2582)
- [ ] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) 
- [x] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) (already the latest)
- [x] [VMware Cloud Director CSI](https://github.com/vmware/cloud-director-named-disk-csi-driver) (#2576)

### Addons

- [x] [Restic Backups](https://github.com/kubermatic/kubeone/tree/main/addons/backups-restic) (#2579)
- [x] [Unattended upgrades](https://github.com/kubermatic/kubeone/tree/main/addons/unattended-upgrades) (#2579)
- [x] [Secret Store CSI driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) (#2579)
- [x] [Vault CSI Secret Provider](https://github.com/hashicorp/vault-csi-provider) (#2579)

Relevant to

**Comment by xmudrii** [comment]
Replaced with #2782
