### ISSUE TITLE
Support Kubernetes 1.27

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2781]
This is a collector issue for Kubernetes 1.27 support in KubeOne. The following tasks should be taken care of:

* [x] Check the Kubernetes changelog to ensure there are no breaking changes and removals
* [x] Update the `build` image to update Sonobuoy (and other dependencies if needed)
* [x] Update the latest supported Kubernetes version in [the API validation](https://github.com/kubermatic/kubeone/blob/main/pkg/apis/kubeone/validation/validation.go#L40-L41) (#2812)
* [x] Update [default admission controllers](https://github.com/kubermatic/kubeone/blob/main/pkg/kubeflags/data.go) if needed (#2812)
* [x] Update [the stable version marker in Makefile](https://github.com/kubermatic/kubeone/blob/5273f9a372736569c6b09b38f2959019d29e4d6a/Makefile#L24) (#2812)
* [x] Update [machine-controller and operating-system-manager](https://github.com/kubermatic/kubeone/blob/a5c3a14725bf135cb2682c4ec96d5872b165b98f/pkg/templates/images/images.go#L222-L224) (#2812)
* [x] Add E2E tests (#2812)
* [x] Update daily periodics to use the latest Kubernetes release
* [x] Update [the Compatibility Matrix](https://docs.kubermatic.com/kubeone/main/architecture/compatibility/supported-versions/) (https://github.com/kubermatic/docs/pull/1492)
* [x] Create an issue to track updating [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) (#2782)
* [x] Run the full conformance tests suite using [Sonobuoy](https://github.com/vmware-tanzu/sonobuoy) (#2850)

**Comment by kron4eg** [comment]
all tasks done
