### ISSUE TITLE
Update images to support Kubernetes 1.27

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2782]
Reference to the previous issue for updating images: #2562

Action items:

- [x] Update the issue template to add/remove [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) as appropriate

The following components/images should be updated:

### General

- [x] [Canal CNI](https://github.com/projectcalico/calico) (#2799)
- [x] [Calico VXLAN CNI](https://github.com/projectcalico/calico) #2844
- [x] [Cilium CNI](https://github.com/cilium/cilium) (#2799)
- [x] [NodeLocalDNS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) (#2813)
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) (#2813)
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) (#2842)

### Cloud provider components

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) (#2820)
- [x] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) (#2820)
- [x] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) #2830
- [x] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) #2831
- [x] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) #2831
- [x] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) #2840
- [x] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) #2840
- [x] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) #2841
- [x] [GCP Compute Persistent Disk CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) #2843
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) #2825
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) #2774
- [x] [Nutanix CSI](https://github.com/nutanix/helm) #2817 
- [x] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) #2819
- [x] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) #2819
- [x] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) #2826
- [x] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) #2826
- [x] [VMware Cloud Director CSI](https://github.com/vmware/cloud-director-named-disk-csi-driver) #2827

### Addons

- [x] [Restic Backups](https://github.com/kubermatic/kubeone/tree/main/addons/backups-restic) #2845
- [x] [Unattended upgrades](https://github.com/kubermatic/kubeone/tree/main/addons/unattended-upgrades) #2845

Relevant to #2781
