### ISSUE TITLE
Test KubeOne 1.7 release

### ISSUE THREAD

**Issue by csengerszabo** [kubermatic/kubeone#2795]
This is a collector Epic for tasks related to testing the KubeOne 1.7 minor release.

- We will release an alpha on the next coming days. Based on this we will conduct our tests and release additional versions as we see fit.
- Features need to be tested on all providers.
- Please create and add all your corresponding testing issues or epics to this Epic as a sub-issue.

```[tasklist]
### Testing issues
- [ ] https://github.com/kubermatic/kubeone/issues/2847
- [ ] https://github.com/kubermatic/kubeone/issues/2848
- [ ] https://github.com/kubermatic/kubeone/issues/2849
- [ ] https://github.com/kubermatic/kubeone/issues/2867
```

**Comment by renchap** [comment]
Is there any timeline for KubeOne 1.7 release yet?

**Comment by kron4eg** [comment]
@renchap we're thinking of the release date somewhere around the end of August.

**Comment by xmudrii** [comment]
This is done
/close
