### ISSUE TITLE
Update auxiliary images to support Kubernetes 1.28

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2835]
Reference to the previous issue for updating images: https://github.com/kubermatic/kubeone/issues/2782

Action items:

- [x] Update the issue template to add/remove [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) as appropriate

The following components/images should be updated:

### General

- [x] [Canal CNI](https://github.com/projectcalico/calico) (#2949)
- [x] [Calico VXLAN CNI](https://github.com/projectcalico/calico) (#2949)
- [x] [Cilium CNI](https://github.com/cilium/cilium) (#2949)
- [x] [NodeLocalDNS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) (already the latest)
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) (#2949)
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) (#2949)

### Cloud provider components

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) 
- [x] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) #3013
- [x] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) #3019
- [x] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) #3019
- [x] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) #3019
- [x] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) #3027
- [x] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) #3026
- [x] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) #3028
- [x] [GCP CCM](https://github.com/kubernetes/cloud-provider-gcp) #3038
- [x] [GCP Compute Persistent Disk CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) #3023
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) #3022
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) #3022
- [x] [Nutanix CCM](https://github.com/nutanix/helm) #3034
- [x] [Nutanix CSI](https://github.com/nutanix/helm) #3029
- [x] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) #3014
- [x] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) #3014
- [x] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) #3018
- [x] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) #3018
- [x] [VMware Cloud Director CSI](https://github.com/vmware/cloud-director-named-disk-csi-driver) #3031 

### Addons

- [x] [Restic Backups](https://github.com/kubermatic/kubeone/tree/main/addons/backups-restic) #3025
- [x] [Unattended upgrades](https://github.com/kubermatic/kubeone/tree/main/addons/unattended-upgrades) #3024

Relevant to #2834

**Comment by kron4eg** [comment]
All the images updated, some added

/close
