### ISSUE TITLE
Update images to support Kubernetes 1.29

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#2998]
Reference to the previous issue for updating images: https://github.com/kubermatic/kubeone/issues/2835

Action items:

- [ ] Update the issue template to add/remove [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) as appropriate

The following components/images should be updated:

### General

- [x] [Canal CNI](https://github.com/projectcalico/calico) #3055
- [x] [Calico VXLAN CNI](https://github.com/projectcalico/calico) 
- [ ] [Cilium CNI](https://github.com/cilium/cilium) #3089
- [x] [NodeLocalDNS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) #3039
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) #3046
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) #3086

### Cloud provider components

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) #3056
- [ ] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) 
- [ ] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) 
- [ ] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) 
- [ ] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) 
- [ ] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) 
- [ ] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) 
- [ ] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) 
- [ ] [GCP Compute Persistent Disk CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) 
- [ ] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) 
- [ ] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) 
- [ ] [Nutanix CSI](https://github.com/nutanix/helm)  
- [ ] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) 
- [ ] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) 
- [ ] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) 
- [ ] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) 
- [ ] [VMware Cloud Director CSI](https://github.com/vmware/cloud-director-named-disk-csi-driver) 

### Addons

- [ ] [Restic Backups](https://github.com/kubermatic/kubeone/tree/main/addons/backups-restic) 
- [ ] [Unattended upgrades](https://github.com/kubermatic/kubeone/tree/main/addons/unattended-upgrades) 
- [ ] [Secret Store CSI driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) 
- [ ] [Vault CSI Secret Provider](https://github.com/hashicorp/vault-csi-provider) 

Relevant to #2997
