### ISSUE TITLE
Test Release KubeOne 1.8

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3103]
This issue is a collector for testing the upcoming [KubeOne 1.8 release](https://github.com/kubermatic/kubeone/milestone/26). Please add any testing issues you have created to the tasklist below:

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubeone/issues/3115
- [ ] https://github.com/kubermatic/kubeone/issues/3126
- [ ] https://github.com/kubermatic/kubeone/issues/3136
```

**Comment by xmudrii** [comment]
All tests are complete.
