### ISSUE TITLE
Test Release KubeOne 1.8 - Test Cluster Provisioning

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3115]
```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubeone/issues/3107
- [ ] https://github.com/kubermatic/kubeone/issues/3108
- [ ] https://github.com/kubermatic/kubeone/issues/3109
- [ ] https://github.com/kubermatic/kubeone/issues/3110
- [ ] https://github.com/kubermatic/kubeone/issues/3111
- [ ] https://github.com/kubermatic/kubeone/issues/3112
- [ ] https://github.com/kubermatic/kubeone/issues/3113
- [ ] https://github.com/kubermatic/kubeone/issues/3114
- [ ] https://github.com/kubermatic/kubeone/issues/3116
```
