### ISSUE TITLE
Test Release KubeOne 1.8 - Test Cluster Upgrading

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3126]
```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubeone/issues/3117
- [ ] https://github.com/kubermatic/kubeone/issues/3118
- [ ] https://github.com/kubermatic/kubeone/issues/3119
- [ ] https://github.com/kubermatic/kubeone/issues/3120
- [ ] https://github.com/kubermatic/kubeone/issues/3121
- [ ] https://github.com/kubermatic/kubeone/issues/3122
- [ ] https://github.com/kubermatic/kubeone/issues/3123
- [ ] https://github.com/kubermatic/kubeone/issues/3124
- [ ] https://github.com/kubermatic/kubeone/issues/3125
```
