### ISSUE TITLE
Update images to support Kubernetes 1.30

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3206]
Reference to the previous issue for updating images: 

Action items:

- [ ] Update the issue template to add/remove [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) as appropriate

The following components/images should be updated:

### General

- [x] [Canal CNI](https://github.com/projectcalico/calico) (#3216)
- [ ] [Calico VXLAN CNI](https://github.com/projectcalico/calico) 
- [x] [Cilium CNI](https://github.com/cilium/cilium) (#3214)
- [x] [NodeLocalDNS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) (#3214)
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) (#3209)
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) (#3214)

### Cloud provider components

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) (#3214)
- [x] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) (#3214)
- [x] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) (#3214)
- [x] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) (#3214)
- [x] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) (#3214)
- [x] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) (#3214)
- [x] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) (#3214)
- [x] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) (already the latest)
- [ ] [GCP CCM](https://github.com/kubernetes/cloud-provider-gcp)  
- [x] [GCP Compute Persistent Disk CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) (#3214)
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) (already the latest)
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) (#3214)
- [ ] [Nutanix CCM](https://github.com/nutanix/helm) 
- [ ] [Nutanix CSI](https://github.com/nutanix/helm)  
- [x] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) (#3214)
- [x] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) (#3214)
- [x] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) (#3214)
- [x] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) (#3214)
- [ ] [VMware Cloud Director CSI](https://github.com/vmware/cloud-director-named-disk-csi-driver) 

### Addons

- [x] [Restic Backups](https://github.com/kubermatic/kubeone/tree/main/addons/backups-restic) (#3214)
- [ ] [Unattended upgrades](https://github.com/kubermatic/kubeone/tree/main/addons/unattended-upgrades) 

Relevant to #3205

**Comment by xmudrii** [comment]
/reopen
Not all components are updated
