### ISSUE TITLE
Test Release KubeOne 1.8.1

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3217]
This issue is a collector for testing the upcoming KubeOne 1.8.1 release. Please add any testing issues you have created to the tasklist below:

```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubeone/issues/3218
- [ ] https://github.com/kubermatic/kubeone/issues/3219
- [ ] https://github.com/kubermatic/kubeone/issues/3283
```
