### ISSUE TITLE
Test Release KubeOne 1.8.1 - Test Cluster Provisioning

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3218]
```[tasklist]
### Tasks
- [ ] https://github.com/kubermatic/kubeone/issues/3220
- [ ] https://github.com/kubermatic/kubeone/issues/3221
- [ ] https://github.com/kubermatic/kubeone/issues/3222
- [ ] https://github.com/kubermatic/kubeone/issues/3223
- [ ] https://github.com/kubermatic/kubeone/issues/3224
- [ ] https://github.com/kubermatic/kubeone/issues/3225
- [ ] https://github.com/kubermatic/kubeone/issues/3226
- [ ] https://github.com/kubermatic/kubeone/issues/3227
- [ ] https://github.com/kubermatic/kubeone/issues/3228
```
