### ISSUE TITLE
Support Kubernetes 1.31

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3346]
This is a collector issue for Kubernetes 1.31 support in KubeOne. The following tasks should be taken care of:

* [x] Check the Kubernetes changelog to ensure there are no breaking changes and removals
* [x] Update the `build` image to update Sonobuoy (and other dependencies if needed) (#3358)
* [x] Update the latest supported Kubernetes version in [the API validation](https://github.com/kubermatic/kubeone/blob/main/pkg/apis/kubeone/validation/validation.go#L40-L41) (#3358)
* [x] Update [default admission controllers](https://github.com/kubermatic/kubeone/blob/main/pkg/kubeflags/data.go) if needed (not needed)
* [x] Update `pause` image version in `pkg/apis/kubeone/helpers.go` if needed (#3358)
* [x] Add the appropriate `cri-tools` version in `pkg/scripts/os_flatcar.go` (#3358)
* [x] Update [the stable version marker in Makefile](https://github.com/kubermatic/kubeone/blob/5273f9a372736569c6b09b38f2959019d29e4d6a/Makefile#L24) (#3358)
* [x] Add E2E tests inside `tests.yml` (#3358)
* [x] Update daily periodics to use the latest Kubernetes release
* [x] Update [the Compatibility Matrix](https://docs.kubermatic.com/kubeone/main/architecture/compatibility/supported-versions/) (https://github.com/kubermatic/docs/pull/1737)
* [x] Create an issue to track updating [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) (#3347)

Tips & Tricks:

* Sometimes the image tag does no match any official GitHub Release name. In these cases `crane ls <url of the image>` can be used to check if a new version of an image exists. Nonetheless, changelog still needs to be checked if the new version introduces any breaking changes
* Default Admission Controllers can be obtained via `docker run --rm registry.k8s.io/kube-apiserver:v${KUBERNETES_VERSION} kube-apiserver -h | grep "admission-control"`

**Action items:**

```[tasklist]
### Tasks
- [x] https://github.com/kubermatic/kubeone/pull/3360
- [x] https://github.com/kubermatic/kubeone/pull/3361
- [ ] https://github.com/kubermatic/kubeone/pull/3387
```
