### ISSUE TITLE
Update images to support Kubernetes 1.31

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#3347]
Reference to the previous issue for updating images: 

Action items:

- [ ] Update the issue template to add/remove [images](https://github.com/kubermatic/kubeone/blob/main/pkg/templates/images/images.go) as appropriate 

The following components/images should be updated:

### General

- [x] [machine-controller](https://github.com/kubermatic/machine-controller) (#3410)
- [x] [operating-system-manager](https://github.com/kubermatic/operating-system-manager) (#3410)
- [x] [metrics-server](https://github.com/kubernetes-sigs/metrics-server) (#3411)
- [x] [NodeLocalDNS](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml) (already the latest)
- [x] [Cluster Autoscaler](https://github.com/kubernetes/autoscaler) (already the latest)

### CNIs

- [x] [Canal CNI](https://github.com/projectcalico/calico) 
- [x] [Calico VXLAN CNI](https://github.com/projectcalico/calico) 
- [ ] [Cilium CNI](https://github.com/cilium/cilium) 

### Cloud provider components

- [x] [AWS CCM](https://github.com/kubernetes/cloud-provider-aws) (#3410)
- [x] [AWS CSI](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) (#3410)
- [x] [Azure CCM](https://github.com/kubernetes-sigs/cloud-provider-azure) (#3410)
- [x] [AzureDisk CSI](https://github.com/kubernetes-sigs/azuredisk-csi-driver) (#3410)
- [x] [AzureFile CSI](https://github.com/kubernetes-sigs/azurefile-csi-driver) (#3410)
- [x] [DigitalOcean CCM](https://github.com/digitalocean/digitalocean-cloud-controller-manager) (#3410)
- [x] [DigitalOcean CSI](https://github.com/digitalocean/csi-digitalocean) (#3410)
- [x] [EquinixMetal CCM](https://github.com/equinix/cloud-provider-equinix-metal) (#3410)
- [x] [GCP CCM](https://github.com/kubernetes/cloud-provider-gcp)  (already the latest)
- [x] [GCP Compute Persistent Disk CSI](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver) (#3410)
- [x] [Hetzner CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager) (#3410)
- [x] [Hetzner CSI](https://github.com/hetznercloud/csi-driver) (#3410)
- [x] [Nutanix CCM](https://github.com/nutanix/helm) (#3410)
- [x] [Nutanix CSI](https://github.com/nutanix/helm) (#3410)
- [x] [OpenStack CCM](https://github.com/kubernetes/cloud-provider-openstack) (#3410)
- [x] [OpenStack CSI](https://github.com/kubernetes/cloud-provider-openstack) (#3410)
- [x] [vSphere CCM](https://github.com/kubernetes/cloud-provider-vsphere) (#3410)
- [x] [vSphere CSI](https://github.com/kubernetes-sigs/vsphere-csi-driver) (#3410)
- [x] [VMware Cloud Director CSI](https://github.com/vmware/cloud-director-named-disk-csi-driver) (already the latest)
- [x] [External Snapshotter](https://github.com/kubernetes-csi/external-snapshotter) (#3410)

### Addons

- [x] [Restic Backups](https://github.com/kubermatic/kubeone/tree/main/addons/backups-restic) (#3412)
- [x] [Unattended upgrades](https://github.com/kubermatic/kubeone/tree/main/addons/unattended-upgrades) (already the latest)

Relevant to #3346
