### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#372]
## Refactor tests

We should refactor all tests suites so we improve stability of KubeOne and the CI pipeline. There are multiple problems that should be addressed by this issue:

* Unit tests coverage is very bad,
* E2E tests are flaking a lot,
* We don't run E2E tests for all providers,
* Our E2E tests are potentially too repetitive,
* It takes a lot of time to merge a PR,
* It's hard to test is everything working locally without spending money,
* It often happens that we leave plenty of hanging cloud resources on all providers.

### E2E provider-coverage

* [ ] [Add E2E tests for GCP (#388)](https://github.com/kubermatic/kubeone/issues/388)
* [ ] [Add E2E tests for OpenStack (#404)](https://github.com/kubermatic/kubeone/issues/404)
* [ ] [Add E2E tests for Packet (#403)](https://github.com/kubermatic/kubeone/issues/403)
* [ ] Consider testing are all CNI plugins working

### E2E general

* [ ] [Run full "conformance" test suite (#158)](https://github.com/kubermatic/kubeone/issues/158)
* [ ] [Use Ginkgo directly in E2E tests (#162)](https://github.com/kubermatic/kubeone/issues/162)
* [ ] Add `kubeone` prefix to E2E resources
