### ISSUE TITLE
Refactor error handling and logging

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#385]
So far we have not paid attention to how we log errors, how we chain errors and what are contents of the error messages. We should refactor the error handling and logging, so it's easier to follow what's going on, what's exactly the error and how to fix the encountered error.

We're using [`logrus`](https://github.com/sirupsen/logrus) which brings structured logging and many other nice features, but in some cases it's inconsistent and it's hard to accomplish some tasks. For example, handling multiple errors, error slices and lists is usually hard.

**Acceptance criteria/tasks:**

* [ ] Errors are chained properly
* [ ] The error messages are clear to the user
* [ ] The error messages contain guidelines and/or link to the documentation for how to fix the encountered error
* [ ] Log messages are improved to be more descriptive, so it's clear to the user what's happening
* [ ] There is a wrapper around `logrus` which makes it possible to easier handle errors
* [ ] We don't show the `cobra` help output on error
* [ ] Logging in E2E tests is improved, so it's easier to follow the progress and debug errors
