### ISSUE TITLE
Automate creation of worker nodes

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubeone#4]
In contrast to master nodes, *worker* nodes must be created using the Cluste API, i.e. by deploying our machine-controller to the cluster and then creating machine resources. _Who_ creates these machine resources is not part of this epic.

* [x] #19 - Create machine-controller deployment
* [x] #23 - Handle cloud provider credentials
* [x] #20 - Check RBAC addon for missing permissions
* [x] #35 - Figure out why machine-controller 0.9.9 is not spawning nodes
* [x] #34 - Fix worker machine creation
* [x] #39 - EC2 Instances do not join the cluster
