### ISSUE TITLE
Add KubeOne to package managers

### ISSUE THREAD

**Issue by xmudrii** [kubermatic/kubeone#471]
We should consider adding KubeOne to the most popular package managers, so it's easy to get KubeOne.

* [ ] #435 Add KubeOne to Homebrew package manager
* [x] #470 Create AUR package for KubeOne
* [ ] #473 Distribute a Docker image of KubeOne
* [ ] #472 Sign releases with GPG
* [x] #480 Add additional sub commands for packagers

Relevant to #436
