### ISSUE TITLE
E2E & Conformance Testing

### ISSUE THREAD

**Issue by kdomanski** [kubermatic/kubeone#6]
Set up E2E & conformance testing for the minimal combination

* [x] #42 - provision and deprovision e2e infra with terraform in drone
* [x] #43 - run kubeone install in drone
* [x] #44 - run some basic kubectl commands on top of newly created e2e cluster from drone
