### ISSUE TITLE
E2E tests for kubeone

### ISSUE THREAD

**Issue by p0lyn0mial** [kubermatic/kubeone#94]
**User Story** As a developer I'd like to write and run tests that would exercise kubernetes clusters created with `kubeone`. 

**Acceptance criteria**:
- test scenarios are written just like normal unit tests using standard go library.
- conformance tests are executed as a basic suite of tests.
- it builds and runs on `prow`

**Tasks**:
* [x] move out to `prow`  (#95)
* [x] implement a package to execute e2e tests (#96)
* [x] remove drone configuration (#104)
